const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s);const maxHealth=5;let milestones=[],W=0,H=0,dpr=1,state='ready',lane=1,visualLane=1,elapsed=0,score=0,health=maxHealth,last=0,spawn=0,objects=[],seen=new Set(),sound=false,audio=null,flash=0,shake=0,passed=0;
let spaceTime=0,spaceX=0,spaceMomentum=0,spin=0,spacePickups=[],fragments=[],spaceBonus=0,pausedFrom='playing',endedInSpace=false;
let cardSchedule=[],currentRoute=0,routeCount=2,archivePaused=false,runNumber=0;
let pro=false,driveX=0,steerVelocity=0,steerKeys=new Set(),pointerDown=false,particles=[],combo=0,comboClock=0,invulnerable=0,enginePhase=0;
let spawnIndex=0,pickupPath=[],surgeTime=0,sweeps=0;
try{pro=localStorage.getItem('the-curve-pro')==='true'}catch{}
$('#mode').textContent=pro?'DRIVE: PRO':'DRIVE: CLASSIC';
try{runNumber=Number(localStorage.getItem('the-curve-next-route'))||0}catch{}
const duration=105,startDate=Date.parse('2014-06-01'),endDate=Date.parse('2026-09-13');
function timelineProgress(t){return 1-Math.pow(1-Math.max(0,Math.min(1,t)),1.7)}
function timeForDate(date){let f=Math.max(0,Math.min(1,(Date.parse(date)-startDate)/(endDate-startDate)));return duration*(1-Math.pow(1-f,1/1.7))}
const trackMoments=[
 {date:'2016-03-15',headline:'GO: SOLVED.',detail:'ALPHAGO · LEE SEDOL',color:'#ff66b5'},
 {date:'2017-12-05',headline:'CHESS: SOLVED.',detail:'ALPHAZERO · SELF-PLAY',color:'#ffe18a'},
 {date:'2020-11-30',headline:'PROTEIN STRUCTURES: SOLVED.',detail:'ALPHAFOLD 2 · STRUCTURE PREDICTION',color:'#6ff5f0'},
 {date:'2025-07-21',headline:'MATH: SOLVED.',detail:'IMO GOLD · MORE PROBLEMS AHEAD',color:'#ffe18a'},
 {date:'2025-09-17',headline:'CODING: SOLVED.',detail:'ICPC GOLD · BUGS STILL EXIST',color:'#ff78c7'}
];
const compute=document.createElement('aside');compute.className='compute-chart';compute.innerHTML='<div class="compute-head"><span>AI COMPUTE MOMENTUM</span><a href="https://epoch.ai/data-insights/ai-chip-production" target="_blank" rel="noopener noreferrer">EPOCH AI ↗</a></div><svg viewBox="0 0 260 126" role="img" aria-label="Illustrative AI compute growth index from 2014 to 2026, drawn month by month on a logarithmic scale"><path class="compute-grid" d="M22 15V99H246 M22 99H246 M22 58H246 M22 15H246"/><path id="compute-path" d=""/><circle id="compute-dot" r="3" cx="22" cy="99"/><text x="20" y="120">2014</text><text x="111" y="120">2020</text><text x="211" y="120">2026</text></svg><div class="compute-note"><span id="compute-value">1× · 2014-06</span><span>INDEX · 2014 = 1</span></div><small>Illustrative backcast to 2014; 2022+ follows Epoch chip-stock trend. Log scale.</small>';$('.stage').append(compute);
let chartMonth=-999;
const computeMonths=147,backcastMonths=91;
function computeIndex(month){return month<=backcastMonths?Math.pow(2.6,month/12):Math.pow(2.6,backcastMonths/12)*Math.pow(3.4,(month-backcastMonths)/12)}
function drawCompute(now){let d=new Date(now),month=Math.max(0,Math.min(computeMonths,(d.getUTCFullYear()-2014)*12+d.getUTCMonth()-5));if(month===chartMonth)return;chartMonth=month;let path='',maxLog=Math.log(computeIndex(computeMonths));for(let m=0;m<=month;m++){let x=22+224*m/computeMonths,y=99-84*Math.log(computeIndex(m))/maxLog;path+=(m?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)+' '}$('#compute-path').setAttribute('d',path);let value=computeIndex(month),x=22+224*month/computeMonths,y=99-84*Math.log(value)/maxLog;$('#compute-dot').setAttribute('cx',x);$('#compute-dot').setAttribute('cy',y);$('#compute-value').textContent=`${value<100?value.toFixed(1):Math.round(value).toLocaleString()}× · ${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`}
fetch('milestones.json').then(r=>r.json()).then(data=>{milestones=data.sort((a,b)=>a.date.localeCompare(b.date));$('#latest').textContent=`${data.length} sourced milestones · 2012–2026`;const years=data.reduce((o,m)=>{let y=m.date.slice(0,4);o[y]=(o[y]||0)+1;return o},{});$('#year-counts').innerHTML=Object.entries(years).map(([year,count])=>`<span>${year}<b>${count}</b></span>`).join('');$('#milestones').innerHTML=data.map(m=>`<a href="${m.url}" target="_blank" rel="noopener noreferrer"><time>${m.date.slice(0,7)}</time><b>${m.title}</b><small>${m.category} ↗</small></a>`).join('');if(state==='playing')buildCardSchedule()}).catch(()=>{$('#latest').textContent='Milestone feed unavailable';$('#archive-panel').hidden=false});
function resize(){let b=canvas.getBoundingClientRect();W=b.width;H=b.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function beep(freq=400,len=.07,type='sine'){if(!sound)return;try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+len)}catch{}}
function project(z,x=0){let t=Math.max(0,1-z);let rise=Math.pow(t,.82);let y=H*(.23+.8*rise);let width=W*(.035+.46*Math.pow(t,1.4));let bend=Math.sin(elapsed*.18+z*2.5)*W*.035*z;return{x:W/2+bend+x*width,y,w:width}}
function approach(base,travel){return ((base-travel)%1+1)%1}
function line(x1,y1,x2,y2,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(...points[0]);for(let i=1;i<points.length;i++)ctx.lineTo(...points[i]);ctx.closePath();ctx.fill()}
function background(t){let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#100d2b');sky.addColorStop(.47,'#432050');sky.addColorStop(1,'#150d35');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);let sunX=W*.5,sunY=H*.25,r=Math.min(W,H)*.16;let glow=ctx.createRadialGradient(sunX,sunY,1,sunX,sunY,r*2);glow.addColorStop(0,'#ffb27a77');glow.addColorStop(1,'#ff3c9400');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H*.7);ctx.fillStyle='#ff8f8d';ctx.beginPath();ctx.arc(sunX,sunY,r,Math.PI,0);ctx.fill();for(let i=0;i<7;i++){let y=sunY+i*r*.17;line(sunX-r,y,sunX+r,y,'#291539',i*.75+1)}
 ctx.fillStyle='#16102e';ctx.beginPath();ctx.moveTo(0,H*.43);for(let x=0;x<=W;x+=20)ctx.lineTo(x,H*(.43+.045*Math.sin(x*.016)+.03*Math.sin(x*.044)));ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();
 for(let side of [-1,1])for(let i=0;i<13;i++){let z=approach(i/13,elapsed*(.035+t*.17)),p=project(z,side*2.7),h=(1-z)*H*.18;line(p.x,p.y,p.x,p.y-h,side<0?'#3c89b970':'#e047aa70',Math.max(1,(1-z)*3));line(p.x-8*(1-z),p.y-h,p.x+8*(1-z),p.y-h,'#6ce5f680',2)}
}
function road(t){let left=[],right=[];for(let i=0;i<=80;i++){let p=project(i/80);left.push([p.x-p.w,p.y]);right.push([p.x+p.w,p.y])}poly([...left,...right.reverse()],'#10112d');for(let i=0;i<80;i++){let z=i/80,p=project(z),q=project((i+1)/80);line(p.x-p.w,p.y,q.x-q.w,q.y,'#ff4dab',2.5+(1-z)*3);line(p.x+p.w,p.y,q.x+q.w,q.y,'#39e1ed',2.5+(1-z)*3)}for(let l of [-1/3,1/3])for(let i=0;i<22;i++){let z=approach(i/22,elapsed*(.025+t*.22)),q=project(Math.min(z+.025,1),l),p=project(z,l);line(p.x,p.y,q.x,q.y,'#d8b4ea'+(z<.8?'90':'44'),Math.max(1,3*(1-z)))}for(let i=0;i<18;i++){let z=approach(i/18,elapsed*(.019+t*.19)),p=project(z);line(p.x-p.w,p.y,p.x+p.w,p.y,`rgba(150,64,191,${.04+(1-z)*.14})`,1)}
 // The upward curling sidewalls make the road read as a rising exponential ramp.
 for(let side of [-1,1])for(let i=0;i<45;i++){let z=i/45,p=project(z,side),q=project((i+1)/45,side);line(p.x,p.y,p.x+side*(1-z)*W*.12,p.y-(1-z)*H*.14,'#a637a826',1);if(i%4===0)line(p.x+side*(1-z)*W*.12,p.y-(1-z)*H*.14,q.x+side*(1-z)*W*.12,q.y-(1-z)*H*.14,'#ae4ce455',1)}
}
function drawRush(t){ctx.save();ctx.lineCap='round';for(let side of [-1,1])for(let i=0;i<17;i++){let z=approach(i/17,elapsed*(.075+t*.44)),p=project(z,side*(1.36+(i%3)*.23)),q=project(Math.min(1,z+.025+t*.04),side*(1.36+(i%3)*.23));let alpha=Math.max(0,(1-z)*(.08+t*.44));line(p.x,p.y,q.x,q.y,side<0?`rgba(255,90,188,${alpha})`:`rgba(74,231,255,${alpha})`,1+(1-z)*t*3)}ctx.restore();drawTrackMoments(t);drawBreakEdge(t)}
function drawTrackMoments(t){for(let moment of trackMoments){let at=timeForDate(moment.date),z=.94-(elapsed-at+3)*.15;if(z<.14||z>.94||(t>.9&&z>breakDepth(t)))continue;let p=project(z),scale=Math.max(.2,1-z),font=Math.min(47,Math.max(9,p.w*.22)),alpha=Math.min(1,(z-.14)*8,(.94-z)*8);ctx.save();ctx.globalAlpha=alpha;ctx.translate(p.x,p.y);ctx.scale(1,.48);ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor=moment.color;ctx.shadowBlur=13*scale;ctx.fillStyle=moment.color;ctx.font=`900 ${font}px 'Barlow Condensed',sans-serif`;ctx.fillText(moment.headline,0,-font*.42,p.w*1.65);ctx.shadowBlur=0;ctx.fillStyle='#ecebff';ctx.font=`500 ${Math.max(7,font*.34)}px 'DM Mono',monospace`;ctx.fillText(moment.detail,0,font*.72,p.w*1.65);ctx.restore();let w=p.w*.72;line(p.x-w,p.y+font*.34,p.x+w,p.y+font*.34,moment.color+'88',Math.max(1,scale*2))}}
function breakDepth(t){return .98-.72*Math.pow(Math.max(0,(t-.9)/.1),1.2)}
function drawBreakEdge(t){if(t<=.9)return;let z=breakDepth(t),p=project(z),far=project(1),blink=.65+.35*Math.sin(elapsed*13);poly([[p.x-p.w,p.y],[far.x-far.w,far.y],[far.x+far.w,far.y],[p.x+p.w,p.y]],'#130b26');ctx.save();ctx.shadowColor='#ff263f';ctx.shadowBlur=22;let jag=[];for(let i=0;i<=18;i++){let x=p.x-p.w+2*p.w*i/18,y=p.y+(i%2?8:-6)*(1-z);jag.push([x,y])}for(let i=0;i<18;i++)line(...jag[i],...jag[i+1],`rgba(255,55,75,${blink})`,4+(1-z)*5);ctx.restore();for(let side of [-1,1]){let x=p.x+side*p.w;line(x,p.y,x,p.y-28*(1-z),'#ff667a',3);line(x-side*13*(1-z),p.y-28*(1-z),x+side*13*(1-z),p.y-28*(1-z),'#ff667a',4)}ctx.fillStyle=`rgba(255,114,133,${blink})`;ctx.font=`700 ${Math.max(12,17*(1-z))}px 'DM Mono',monospace`;ctx.textAlign='center';ctx.fillText('ROAD ENDS',p.x,p.y-35*(1-z))}
function drawCarShadow(x,y,s){ctx.save();ctx.fillStyle='#04071499';ctx.beginPath();ctx.ellipse(x,y+7*s,37*s,12*s,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3cefff3d';ctx.beginPath();ctx.ellipse(x,y+4*s,28*s,6*s,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawCar(x,y,s,enemy=false,variant=0,lean=0){let w=48*s,h=76*s,body=enemy?['#ee5b77','#ef9d57','#9b76ea'][variant%3]:'#19d8e6',edge=enemy?'#ffc4aa':'#a8fbff';ctx.save();ctx.translate(x,y);ctx.rotate(lean);ctx.shadowColor=enemy?body:'#41edff';ctx.shadowBlur=20*s;
 poly([[-w*.47,-h*.1],[-w*.42,-h*.72],[-w*.26,-h*.98],[w*.26,-h*.98],[w*.42,-h*.72],[w*.47,-h*.1],[w*.39,0],[-w*.39,0]],body);ctx.shadowBlur=0;
 poly([[-w*.32,-h*.68],[-w*.22,-h*.9],[w*.22,-h*.9],[w*.32,-h*.68]],'#14223e');poly([[-w*.35,-h*.57],[w*.35,-h*.57],[w*.29,-h*.35],[-w*.29,-h*.35]],'#162442');
 poly([[-w*.47,-h*.38],[-w*.34,-h*.46],[-w*.34,-h*.08],[-w*.5,-h*.05]],'#0a1029');poly([[w*.47,-h*.38],[w*.34,-h*.46],[w*.34,-h*.08],[w*.5,-h*.05]],'#0a1029');
 line(-w*.4,-h*.67,w*.4,-h*.67,edge,1.5*s);line(-w*.32,-h*.31,w*.32,-h*.31,edge,1.3*s);line(-w*.39,-h*.08,w*.39,-h*.08,'#0c1733',3*s);
 ctx.fillStyle=enemy?'#ffe89b':'#ff52b5';ctx.fillRect(-w*.39,-h*.18,w*.22,h*.075);ctx.fillRect(w*.17,-h*.18,w*.22,h*.075);ctx.fillStyle='#0a1029';ctx.fillRect(-w*.3,-h*.02,w*.6,h*.045);
 if(!enemy){ctx.fillStyle='#ffe4a8';ctx.fillRect(-w*.16,-h*.97,w*.32,h*.045);line(-w*.54,-h*.02,-w*.54,-h*.22,'#58ecff',2*s);line(w*.54,-h*.02,w*.54,-h*.22,'#58ecff',2*s)}ctx.restore()}
function burst(x,y,color,count=16){for(let i=0;i<count;i++){let a=Math.random()*Math.PI*2,v=50+Math.random()*170;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.35+Math.random()*.5,max:.85,color,size:2+Math.random()*4})}}
function updateParticles(dt){for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.28,dt);p.vy*=Math.pow(.28,dt);p.life-=dt}particles=particles.filter(p=>p.life>0)}
function drawParticles(){ctx.save();for(let p of particles){ctx.globalAlpha=Math.min(1,p.life/p.max);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=12;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.restore()}
function drawPickup(x,y,s,tier=0){let colors=['#5cecf5','#ff65c3','#ffd36e'],color=colors[tier];ctx.save();ctx.translate(x,y);ctx.rotate(elapsed*(tier===2?1.2:2)+spaceTime*2);ctx.shadowColor=color;ctx.shadowBlur=(tier===2?34:25)*s;if(tier===0)poly([[0,-23*s],[17*s,0],[0,23*s],[-17*s,0]],color);else if(tier===1)poly([[0,-25*s],[18*s,-11*s],[18*s,11*s],[0,25*s],[-18*s,11*s],[-18*s,-11*s]],color);else{let points=[];for(let i=0;i<10;i++){let a=-Math.PI/2+i*Math.PI/5,r=(i%2?11:26)*s;points.push([Math.cos(a)*r,Math.sin(a)*r])}poly(points,color)}ctx.shadowBlur=0;ctx.fillStyle=tier===0?'#0d3456':'#241432';ctx.font=`700 ${Math.round((tier===2?11:15)*s)}px monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(tier===0?'+':tier===1?'2':'4',0,0);ctx.restore()}
function launchSpace(){state='space';spaceTime=0;spaceX=driveX*.35;spaceMomentum=0;spin=0;objects=[];spaceBonus=0;spacePickups=Array.from({length:18},(_,i)=>({x:Math.sin(i*2.37)*.84,y:-.12-i*.18,got:false}));$('#year').textContent='NOW';$('#speed').innerHTML='∞<span class="unit">×</span>';$('#status').textContent='ROAD ENDS · STEER THROUGH THE DEBRIS';$('#latest').textContent='BEYOND THE TIMELINE / LAST CHANCE POINTS';beep(170,.7,'sawtooth')}
function updateSpace(dt){spaceTime+=dt;spaceX=Math.max(-1.1,Math.min(1.1,spaceX+spaceMomentum*dt));spaceMomentum*=Math.pow(.48,dt);spin+=dt*(2.2+spaceTime*.65+spaceMomentum*.7);for(let p of spacePickups){p.y+=dt*(.36+spaceTime*.045);if(!p.got&&p.y>.46&&p.y<.64&&Math.abs(p.x-spaceX)<.23){p.got=true;score+=750;spaceBonus+=750;flash=.2;beep(920,.12)}}$('#score').textContent=String(score).padStart(6,'0');$('#status').textContent=`ZERO-G BONUS +${spaceBonus} · STEER FOR MORE`;shake=Math.max(shake,Math.max(0,spaceTime-3.8)*2.5);flash=Math.max(0,flash-dt*1.7);if(spaceTime>=6.2){state='rupture';spaceTime=0;fragments=Array.from({length:22},(_,i)=>({a:i*2.399,v:70+(i%6)*29,r:6+(i%4)*5}));flash=.85;beep(65,.7,'sawtooth');$('#status').textContent='STRUCTURAL INTEGRITY LOST'}}
function updateRupture(dt){spaceTime+=dt;shake=Math.max(0,16-spaceTime*12);flash=Math.max(0,flash-dt*.9);if(spaceTime>1.4)finish(true)}
function drawSpace(){let flying=state==='space'||(state==='paused'&&pausedFrom==='space');let g=ctx.createRadialGradient(W*.5,H*.55,10,W*.5,H*.55,Math.max(W,H)*.65);g.addColorStop(0,'#40245f');g.addColorStop(.45,'#1a1745');g.addColorStop(1,'#05091d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(flying&&spaceTime<1.2){ctx.save();ctx.globalAlpha=1-spaceTime/1.2;road(1);ctx.restore()}let travel=flying?spaceTime:6.2+spaceTime;for(let i=0;i<100;i++){let a=i*2.39996,r=((i*61.7+travel*(90+i%7*25))%Math.max(W,H))*.68,x=W*.5+Math.cos(a)*r,y=H*.55+Math.sin(a)*r*.68;line(x,y,x-Math.cos(a)*(5+r*.024),y-Math.sin(a)*(5+r*.024),i%4?'#b8baff88':'#ff77c9aa',1+i%4*.3)}for(let p of spacePickups){if(p.got||p.y<-.1||p.y>1.1)continue;drawPickup(W*(.5+p.x*.36),H*p.y,1.05)}if(flying){ctx.save();ctx.translate(W*(.5+spaceX*.36)+(Math.random()-.5)*Math.max(0,spaceTime-4)*7,H*.54+(Math.random()-.5)*Math.max(0,spaceTime-4)*7);ctx.rotate(spin);drawCar(0,0,Math.min(1.8,W/570),false);ctx.restore();if(spaceTime>3.8){ctx.fillStyle='#ff81bc';for(let i=0;i<Math.floor((spaceTime-3.8)*9);i++){let a=i*2.4+spin,r=25+i*4;ctx.fillRect(W*(.5+spaceX*.36)+Math.cos(a)*r,H*.54+Math.sin(a)*r,3,3)}}}else{for(let f of fragments){let x=W*(.5+spaceX*.36)+Math.cos(f.a)*f.v*spaceTime,y=H*.54+Math.sin(f.a)*f.v*spaceTime;ctx.save();ctx.translate(x,y);ctx.rotate(f.a+spaceTime*5);ctx.fillStyle=f.r%2?'#ff58b6':'#40deed';ctx.fillRect(-f.r/2,-f.r/2,f.r,f.r*1.8);ctx.restore()}}ctx.fillStyle='#b2eaf1';ctx.font='700 13px monospace';ctx.textAlign='center';ctx.fillText(flying?'BEYOND THE PRESENT · KEEP STEERING':'THE CAR CANNOT KEEP UP',W/2,H*.18)}
function spawnObject(t){let cruise=[1,1,1,0,0,1,1,2,2],sweep=[0,1,2,2,1,0,1,1],pattern=t<.28?cruise:sweep,lane=pro?Math.floor(Math.random()*3):pattern[spawnIndex%pattern.length],kind=(!pro&&t<.28)||Math.random()<(pro?.31:.93)?'pickup':'car',tier=t<.32?0:t<.68?(spawnIndex%4===0?1:0):(spawnIndex%3===0?2:1);objects.push({lane,z:1,kind,tier,variant:Math.floor(Math.random()*3),hit:false});if(!pro&&kind==='pickup'&&t>.28)objects.push({lane,z:1.11,kind:'pickup',tier,hit:false});spawnIndex++;spawn=0}
function buildCardSchedule(){let eligible=milestones.map((m,i)=>({m,i})).filter(({m})=>Date.parse(m.date)>=startDate);routeCount=Math.max(2,Math.ceil(eligible.length/22));let opening=eligible[0],nextFree=[0,0],selected=eligible.slice(1).filter((_,i)=>i%routeCount===currentRoute);cardSchedule=[];if(opening){cardSchedule.push({m:opening.m,i:opening.i,side:0,start:1.2,end:6});nextFree[0]=6}for(let position=0;position<selected.length;position++){let {m,i}=selected[position],side=position%2,desired=timeForDate(m.date),length=4.8,start=Math.max(Math.min(desired,duration-length),nextFree[side]);nextFree[side]=start+length;cardSchedule.push({m,i,side,start,end:start+length})}for(let side of [0,1]){let sideCards=cardSchedule.filter(c=>c.side===side),shift=Math.min(Math.max(0,nextFree[side]-duration),sideCards[0]?.start||0);for(let card of sideCards){card.start-=shift;card.end-=shift}}}
function collectCrystal(lane,t,p,tier=0){if(pickupPath.at(-1)!==lane)pickupPath.push(lane);pickupPath=pickupPath.slice(-3);let sweep=pickupPath.length===3&&((pickupPath[0]===0&&pickupPath[1]===1&&pickupPath[2]===2)||(pickupPath[0]===2&&pickupPath[1]===1&&pickupPath[2]===0));if(sweep){surgeTime=6;sweeps++;pickupPath=[];score+=600;burst(p.x,p.y-40,'#ffe080',30);beep(1100,.2,'triangle')}let tierValue=[1,2,4][tier],gain=(100+Math.round(t*900)+combo*25)*tierValue*(surgeTime>0?2:1);score+=gain;combo++;comboClock=3.5;flash=.15;burst(p.x,p.y-40,['#5df4ff','#ff65c3','#ffd36e'][tier],18);beep(760+Math.min(combo,8)*35+tier*75,.1);$('#status').textContent=sweep?`DIAGONAL SWEEP +600 · SURGE ×2`:`${['CYAN','PINK ×2','GOLD ×4'][tier]} CRYSTAL +${gain} · ${surgeTime>0?'SURGE ×2':'CHAIN '+combo}`}
function sign(card){
 let {m,side,start,end}=card,age=elapsed-start,remaining=end-elapsed,progress=Math.max(0,Math.min(1,age/(end-start))),z=.92-.5*(1-Math.pow(1-progress,3)),p=project(z);
 let room=side===0?p.x-p.w-18:W-(p.x+p.w)-18,w=Math.max(34,Math.min(282,W*.39,room,(1-z)*430)),h=Math.max(35,Math.min(94,w*.37)),gap=Math.max(8,p.w*.035),x=side===0?p.x-p.w-gap-w:p.x+p.w+gap,y=p.y-h-18*(1-z),fade=Math.max(0,Math.min(1,age/.3,remaining/.35));
 if(w<45||x+w<0||x>W)return;
 let accent=side===0?'#ff59b2':'#48e8f3',metal=side===0?'#905180':'#468a9a',inset=h*.11,footY=p.y+Math.max(5,12*(1-z));
 ctx.save();ctx.globalAlpha=fade;for(let postX of [x+w*.16,x+w*.84]){line(postX,y+h,postX,footY,metal,Math.max(2,w*.018));line(postX-8*(1-z),footY,postX+8*(1-z),footY,accent,2)}
 line(x+w*.16,y+h+6,x+w*.84,footY-2,metal,1.5);line(x+w*.84,y+h+6,x+w*.16,footY-2,metal,1.5);
 let face=side===0?[[x,y+inset],[x+w,y],[x+w,y+h],[x,y+h-inset]]:[[x,y],[x+w,y+inset],[x+w,y+h-inset],[x,y+h]];
 ctx.shadowColor=accent;ctx.shadowBlur=14*(1-z);poly(face,'#11142df2');ctx.shadowBlur=0;
 poly(side===0?[[x-6,y+inset+4],[x,y+inset],[x,y+h-inset],[x-6,y+h-inset+4]]:[[x+w,y+inset],[x+w+6,y+inset+4],[x+w+6,y+h-inset+4],[x+w,y+h-inset]],metal);
 for(let i=0;i<4;i++)line(...face[i],...face[(i+1)%4],accent,Math.max(1,2*(1-z)));
 let pad=Math.max(7,w*.07),font=Math.max(8,Math.min(18,w*.068));ctx.textAlign='left';ctx.fillStyle='#89eff4';ctx.font=`${Math.max(7,font*.67)}px 'DM Mono',monospace`;ctx.fillText(m.date.slice(0,7)+' / '+m.category,x+pad,y+h*.27,w-pad*2);
 ctx.fillStyle='#fff5fb';ctx.font=`700 ${font}px 'Barlow Condensed',sans-serif`;let words=m.title.toUpperCase().split(' '),lines=[''];for(let word of words){let last=lines.length-1,candidate=(lines[last]+' '+word).trim();if(ctx.measureText(candidate).width>w-pad*2&&lines[last]&&lines.length<3)lines.push(word);else lines[last]=candidate}lines.slice(0,3).forEach((text,j)=>ctx.fillText(text,x+pad,y+h*.48+j*font*.94,w-pad*2));ctx.restore()
}
function update(dt){if(state==='space'){updateSpace(dt);updateParticles(dt);return}if(state==='rupture'){updateRupture(dt);updateParticles(dt);return}if(state!=='playing')return;elapsed=Math.min(duration,elapsed+dt);let t=elapsed/duration;enginePhase+=dt*(4+t*27);invulnerable=Math.max(0,invulnerable-dt);comboClock=Math.max(0,comboClock-dt);surgeTime=Math.max(0,surgeTime-dt);if(!comboClock)combo=0;
 if(pro){let input=Number(steerKeys.has(1))-Number(steerKeys.has(-1));steerVelocity+=(input*(2.1+t*.5)-steerVelocity)*Math.min(1,dt*(input?9:7));driveX=Math.max(-.98,Math.min(.98,driveX+steerVelocity*dt));visualLane=1+driveX}else{visualLane+=(lane-visualLane)*Math.min(1,dt*12);driveX=visualLane-1;steerVelocity=(lane-visualLane)*2}
 spawn+=dt;let interval=pro?.95-Math.pow(t,1.7)*.68:1.4-.9*Math.pow(t,1.2);if(spawn>interval)spawnObject(t);let movement=dt*(.3+1.5*Math.pow(t,2));for(let o of objects){o.z-=movement;if(!o.hit&&o.z<.23){o.hit=true;let delta=Math.abs((o.lane-1)-driveX),p=project(.23,driveX*.64);if(delta<(o.kind==='car'?.39:.48)){if(o.kind==='car'){if(!invulnerable){if(pro||t>.35)health--;invulnerable=pro?1.2:2.4;flash=pro?.5:.2;shake=pro?14:5;combo=0;pickupPath=[];burst(p.x,p.y-35,'#ff669e',pro?24:10);beep(90,.2,'sawtooth');$('#status').textContent=pro?'COLLISION · KEEP MOVING':'TRAFFIC BRUSH · KEEP COLLECTING'}}else collectCrystal(o.lane,t,p,o.tier)}else if(o.kind==='car'){let near=delta<.65,gain=near?75+combo*15:25;score+=gain;passed++;if(near){combo++;comboClock=3;burst(p.x,p.y-50,'#ffcc77',9);$('#status').textContent=`NEAR MISS +${gain} · CHAIN ${combo}`;beep(490,.05)}else beep(360,.035)}}}objects=objects.filter(o=>o.z>.14);updateParticles(dt);
 let now=startDate+timelineProgress(t)*(endDate-startDate);for(let i=0;i<milestones.length;i++){let m=milestones[i],ms=Date.parse(m.date);if(ms>=startDate&&ms<=now&&!seen.has(i)){seen.add(i);$('#latest').textContent=`${m.date.slice(0,7)} / ${m.title}`;if(i%3===0)beep(560,.08);score+=50}}$('#year').textContent=new Date(now).getUTCFullYear();$('#speed').innerHTML=String(Math.round(1+99*Math.pow(t,2.5))).padStart(3,'0')+'<span class="unit">×</span>';$('#score').textContent=String(score).padStart(6,'0');$('#health').textContent='♥ '.repeat(health)+'♡ '.repeat(maxHealth-health);$('#progress').style.width=t*100+'%';drawCompute(now);if(health<=0)finish(false);else if(elapsed>=duration)launchSpace();flash=Math.max(0,flash-dt*1.9);shake*=.82}
function render(){let t=elapsed/duration;ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);if(state==='space'||state==='rupture'||endedInSpace||(state==='paused'&&pausedFrom==='space'))drawSpace();else{background(t);road(t);drawRush(t);for(let o of objects){let p=project(o.z,(o.lane-1)*.64),s=.17+1.4*Math.pow(1-o.z,1.7);if(o.kind==='car')drawCar(p.x,p.y,s,true,o.variant);else drawPickup(p.x,p.y-32*s,s,o.tier)}let car=project(.23,driveX*.64),s=Math.min(1.55,W/730),glow=9+Math.sin(enginePhase)*4;drawCarShadow(car.x,car.y,s);ctx.save();ctx.shadowColor='#52edff';ctx.shadowBlur=18+glow;line(car.x-12*s,car.y+3,car.x-18*s,car.y+30+t*55,'#40eaff88',3+t*4);line(car.x+12*s,car.y+3,car.x+18*s,car.y+30+t*55,'#ff4fae99',3+t*4);ctx.restore();if(invulnerable<=0||Math.floor(invulnerable*14)%2===0)drawCar(car.x,car.y+Math.sin(enginePhase*2)*1.5,s,false,0,-steerVelocity*.065);for(let card of cardSchedule)if(elapsed>=card.start&&elapsed<card.end)sign(card)}drawParticles();ctx.restore();$('#flash').style.opacity=flash?flash*.65:0;let active=state==='playing'&&(surgeTime>0||combo>1&&comboClock>0);$('#chain').hidden=!active;if(active){$('#chain').classList.toggle('surge',surgeTime>0);$('#chain-label').textContent=surgeTime>0?'SURGE ×':'CHAIN';$('#chain-count').textContent=surgeTime>0?'2':combo;$('.chain-timer').style.transform=`scaleX(${surgeTime>0?surgeTime/6:comboClock/3.5})`};requestAnimationFrame(frame)}function frame(ts){let dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);render()}requestAnimationFrame(frame);
function start(){state='playing';endedInSpace=false;elapsed=0;lane=1;visualLane=1;driveX=0;steerVelocity=0;steerKeys.clear();particles=[];combo=0;comboClock=0;invulnerable=0;pickupPath=[];surgeTime=0;sweeps=0;spawnIndex=0;score=0;health=maxHealth;$('#health').textContent='♥ '.repeat(maxHealth);spawn=0;passed=0;spaceTime=0;spaceBonus=0;spaceX=0;spaceMomentum=0;spin=0;spacePickups=[];fragments=[];objects=[];seen.clear();let eligibleCount=milestones.filter(m=>Date.parse(m.date)>=startDate).length;routeCount=Math.max(2,Math.ceil(eligibleCount/22));currentRoute=runNumber%routeCount;runNumber++;try{localStorage.setItem('the-curve-next-route',String(runNumber))}catch{}buildCardSchedule();$('#era').textContent=`2014 → 2026 / ROUTE ${currentRoute+1}/${routeCount}`;$('#year').textContent='2014';$('#overlay').hidden=true;$('#pause').disabled=false;$('#pause').textContent='PAUSE';$('#status').textContent=`${pro?'PRO CHALLENGE':'CRYSTAL CRUISE'} · HEADLINE ROUTE ${currentRoute+1}/${routeCount}`;beep(180,.2,'sawtooth')}
function finish(win){state='ended';endedInSpace=win;$('#pause').disabled=true;$('#overlay').hidden=false;$('#overlay').innerHTML=`<div class="eyebrow">${win?'BEYOND THE END OF THE ROAD':'SIGNAL LOST'}</div><h1>${win?'THE FUTURE<br><em>BROKE LOOSE.</em>':'STAY ON<br><em>THE ROAD.</em>'}</h1><p>${win?`You crossed the timeline, made ${sweeps} diagonal sweeps, and grabbed ${spaceBonus.toLocaleString()} points in zero-g before the car came apart.`:'Traffic caught up. Try a new route through the timeline.'} Final score: ${score.toLocaleString()}.</p><button id="restart">DRIVE AGAIN <span>↗</span></button><div class="controls">The next drive shows a different set of cards. The archive has every source.</div>`;$('#restart').onclick=start}
function steer(dir){if(state==='playing'){lane=Math.max(0,Math.min(2,lane+dir));beep(270+lane*100,.04)}else if(state==='space'){spaceMomentum=Math.max(-1.3,Math.min(1.3,spaceMomentum+dir*.58));beep(450+dir*70,.06)}}function togglePause(){if(state==='playing'||state==='space'){pausedFrom=state;state='paused';$('#pause').textContent='RESUME';let visible=pausedFrom==='playing'?cardSchedule.filter(c=>elapsed>=c.start&&elapsed<c.end):[];let details=visible.length?visible.map(c=>`<p class="pause-headline"><small>${c.m.date.slice(0,7)} · ${c.m.category}</small><a href="${c.m.url}" target="_blank" rel="noopener noreferrer">${c.m.title} ↗</a></p>`).join(''):'<p>No headline is passing right now. The archive has the full timeline.</p>';$('#overlay').hidden=false;$('#overlay').innerHTML=`<div class="eyebrow">MOMENTARY STILLNESS</div><h1>PAUSED<span style="color:#ff4fae">.</span></h1>${details}<button id="resume">RESUME DRIVE ↗</button>`;$('#resume').onclick=togglePause}else if(state==='paused'){state=pausedFrom;$('#pause').textContent='PAUSE';$('#overlay').hidden=true}}
$('#start').onclick=start;$('#pause').onclick=togglePause;$('#mode').onclick=()=>{pro=!pro;steerKeys.clear();steerVelocity=0;lane=Math.max(0,Math.min(2,Math.round(driveX+1)));$('#mode').textContent=pro?'DRIVE: PRO':'DRIVE: CLASSIC';$('#status').textContent=pro?'PRO DRIVE · HOLD KEYS OR DRAG TO STEER':'CLASSIC DRIVE · TAP TO CHANGE LANES';try{localStorage.setItem('the-curve-pro',String(pro))}catch{}};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'SOUND ON':'SOUND OFF';if(sound)beep()};$('#archive').onclick=()=>{archivePaused=state==='playing'||state==='space';if(archivePaused)togglePause();$('#archive-panel').hidden=false;$('#archive-panel').scrollIntoView({behavior:'smooth'})};$('#close-archive').onclick=()=>{$('#archive-panel').hidden=true;if(archivePaused&&state==='paused')togglePause();archivePaused=false;$('.stage').scrollIntoView({behavior:'smooth'})};
function keyDirection(code){return code==='ArrowLeft'||code==='KeyA'?-1:code==='ArrowRight'||code==='KeyD'?1:0}
addEventListener('keydown',e=>{let dir=keyDirection(e.code);if(dir||e.code==='Space')e.preventDefault();if(dir){if(pro&&state==='playing')steerKeys.add(dir);else if(!e.repeat)steer(dir)}if(e.code==='Space'&&!e.repeat)togglePause()});addEventListener('keyup',e=>{let dir=keyDirection(e.code);if(dir)steerKeys.delete(dir)});addEventListener('blur',()=>steerKeys.clear());
function pointerSteer(e){let box=canvas.getBoundingClientRect(),x=(e.clientX-box.left)/box.width;if(state==='space'){spaceMomentum=Math.max(-1.3,Math.min(1.3,spaceMomentum+(x-.5)*.7))}else if(state==='playing'&&pro){let target=Math.max(-.98,Math.min(.98,(x-.5)*2.1));steerVelocity+=(target-driveX)*.45;driveX+=(target-driveX)*.18}}
canvas.addEventListener('pointerdown',e=>{pointerDown=true;canvas.setPointerCapture(e.pointerId);if(pro)pointerSteer(e);else steer(e.clientX<canvas.getBoundingClientRect().left+W/2?-1:1)});canvas.addEventListener('pointermove',e=>{if(pointerDown&&pro)pointerSteer(e)});canvas.addEventListener('pointerup',()=>pointerDown=false);canvas.addEventListener('pointercancel',()=>pointerDown=false);
